import 'package:flutter/material.dart';

class ProductModel with ChangeNotifier {
  final String id, title, imageUrl, productCategoryName;
  final double price, salePrice;
  final bool isOnSale, isPiece;
  ProductModel({
    required this.salePrice,
    required this.id,
    required this.title,
    required this.imageUrl,
    required this.isOnSale,
    required this.productCategoryName,
    required this.price,
    required this.isPiece,
  });
  static final List<ProductModel> products = [
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSale: true,
      isPiece: false,
    ),
  ];
}
